version: 0.2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/ubuntu/14.04
      - docker build -t ubuntu:14.04 .
      - cd $CODEBUILD_SRC_DIR/java/openjdk-8
      - docker build -t java:openjdk-8 .
